#!/bin/csh
#
# This works around bug where, by default, macOS 14.0 writes part of a file
# immediately, and then doesn't update the directory for 20-60 seconds, causing
# the file system to be corrupted.
#

set disky=`df | grep KBD | cut -w -f1`
set vol=`df | grep KBD | cut -w -f9`
sudo umount $vol
sudo mkdir $vol
sleep 2
sudo mount -v -o noasync -t msdos $disky $vol
